### ISSUE TITLE
Cannot install some Wally packages on Linux

### ISSUE THREAD

**Issue by SolarHorizon** [pesde-pkg/pesde#19]
When using pesde with Wally packages on Linux, dependency resolution will sometimes hang infinitely. I don't have this issue on Windows and I don't have a MacOS machine to test on.

I am able to consistently reproduce this issue when trying to install `wally#jsdotlua/react-roblox` on Linux.

For a minimal repro:
```toml
name = "test/dependency_resolution"
version = "0.1.0"

[target]
environment = "roblox"

[indices]
default = "https://github.com/pesde-pkg/index"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.1.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.4.4", target = "lune" }

[dependencies]
react-roblox = { wally = "wally#jsdotlua/react-roblox", version = "^17.2.1" }
```
