### ISSUE TITLE
Shorter dependency specification syntax

### ISSUE THREAD

**Issue by alicesaidhi** [pesde-pkg/pesde#28]
It's hard to remember how to specify dependencies currently.

Defining dependencies should be clear, concise and consistent without having 4 different ways to specify 4 different kinds of dependencies. Ideally, this can all be done through a simple and consistent single way. By adding the following as ways to define dependencies, it becomes easier to remember and manually write dependencies if necessary.
```toml
wally = "wally#scope/wally@0.3.1"
github = "gh#scope/github@latest"
pesde = "scope/pesde@0.2.2"
workspace = "workspace#scope/workspace"

index_wally = "wally#scope/wally@0.3.1 index=default"
index_pesde = "scope/pesde@0.2.2 index=default"

target = "scope/pesde@0.2.2 target=luau"
target_and_index = "scope/pesde@0.2.2 index=default target=luau"
```
